# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xYjmRrGNQcLEjsdcuKL-8vZSA7YJDNu
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Constante de Coulomb en SI
K0 = 8.9875517923e9

# ------------------------------------------------------------
# Función que genera la figura (casi igual a tu actualizar())
# ------------------------------------------------------------
def generar_figura(q1_micro, q2_micro, x1, x2, y1, y2, epsilon, lim, npts):
    """
    Recibe parámetros en unidades amigables:
        q1_micro, q2_micro: cargas en microculombios (μC)
        x1, x2, y1, y2: posiciones en metros
        epsilon: permitividad relativa (adimensional)
        lim: límite de los ejes (m)
        npts: número de puntos por dimensión
    Devuelve la figura de matplotlib con los tres subplots.
    """
    # Convertir cargas a Coulombs
    q1 = q1_micro * 1e-6
    q2 = q2_micro * 1e-6

    k = K0 / epsilon
    cargas = [(q1, x1, y1), (q2, x2, y2)]

    # Malla
    x = np.linspace(-lim, lim, npts)
    y = np.linspace(-lim, lim, npts)
    X, Y = np.meshgrid(x, y)

    Ex = np.zeros_like(X)
    Ey = np.zeros_like(Y)
    V = np.zeros_like(X)
    radio_exclusion = 0.10

    for qi, xq, yq in cargas:
        dx = X - xq
        dy = Y - yq
        r = np.sqrt(dx**2 + dy**2)
        mask = r < radio_exclusion
        r = np.where(mask, np.nan, r)
        Ex += k * qi * dx / r**3
        Ey += k * qi * dy / r**3
        V  += k * qi / r

    Emag = np.sqrt(Ex**2 + Ey**2)
    Emag_log = np.log10(Emag + 1e-12)

    # Recorte dinámico del potencial
    V_finite = V[~np.isnan(V)]
    if len(V_finite) > 0:
        vmax_auto = np.percentile(np.abs(V_finite), 95)
        if vmax_auto < 1e-12:
            vmax_auto = 1.0
        Vclip = np.clip(V, -vmax_auto, vmax_auto)
    else:
        Vclip = V

    # Crear figura y subplots
    fig, axes = plt.subplots(1, 3, figsize=(12, 5))

    # --- Gráfica 1: Líneas de campo ---
    ax = axes[0]
    stream = ax.streamplot(X, Y, Ex, Ey,
                           color=Emag_log,
                           cmap='plasma',
                           density=1.8,
                           linewidth=1.2,
                           arrowsize=1.2)
    ax.scatter([x1, x2], [y1, y2],
               c=['red', 'blue'], s=100, label='Cargas')
    ax.set_title("Líneas de campo")
    ax.set_xlabel('x (m)')
    ax.set_ylabel('y (m)')
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.grid(alpha=0.3)
    ax.legend()
    fig.colorbar(stream.lines, ax=ax, label=r'$\log_{10}|E|$ (N/C)')

    # --- Gráfica 2: Potencial ---
    ax = axes[1]
    mapa = ax.contourf(X, Y, Vclip, levels=60, cmap='RdBu_r')
    ax.contour(X, Y, Vclip, levels=20, colors='k', alpha=0.4)
    ax.scatter([x1, x2], [y1, y2],
               c=['red', 'blue'], s=80)
    ax.set_title("Potencial eléctrico")
    ax.set_xlabel('x (m)')
    ax.set_ylabel('y (m)')
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.grid(alpha=0.3)
    fig.colorbar(mapa, ax=ax, label='V (V)')

    # --- Gráfica 3: Magnitud del campo ---
    ax = axes[2]
    campo = ax.contourf(X, Y, Emag_log, levels=50, cmap='inferno')
    ax.scatter([x1, x2], [y1, y2],
               c='white', s=80)
    ax.set_title(r'Magnitud del campo $\log_{10}|E|$')
    ax.set_xlabel('x (m)')
    ax.set_ylabel('y (m)')
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.grid(alpha=0.3)
    fig.colorbar(campo, ax=ax, label=r'$\log_{10}|E|$ (N/C)')

    # Título general
    fig.suptitle(
        f'Sistema de cargas | εᵣ = {epsilon:.3f} | k = {k:.3e} N·m²/C²',
        fontsize=12
    )
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    return fig

# ------------------------------------------------------------
# INTERFAZ CON STREAMLIT
# ------------------------------------------------------------

st.set_page_config(page_title="Simulación de Campo Eléctrico", layout="wide")
st.title("⚡ Simulación del Campo Eléctrico de un Dipolo")

# Crear columnas para organizar la interfaz
# Usamos una columna estrecha para los controles y otra ancha para la gráfica
col1, col2 = st.columns([1, 3], gap="medium")

with col1:
    st.header("Parámetros")
    q1 = st.slider("Carga 1 (q1) [μC]", -3.0, 3.0, 1.0, 0.1)
    q2 = st.slider("Carga 2 (q2) [μC]", -3.0, 3.0, -1.0, 0.1)
    x1 = st.slider("Posición x1 [m]", -2.0, 2.0, -1.0, 0.1)
    x2 = st.slider("Posición x2 [m]", -2.0, 2.0, 1.0, 0.1)
    y1 = st.slider("Posición y1 [m]", -2.0, 2.0, 0.0, 0.1)
    y2 = st.slider("Posición y2 [m]", -2.0, 2.0, 0.0, 0.1)
    epsilon = st.slider("Permitividad relativa (εᵣ)", 0.1, 5.0, 1.0, 0.1)
    lim = st.slider("Límite de ejes [m]", 1.0, 5.0, 3.0, 0.5)
    npts = st.slider("Puntos por dimensión", 30, 120, 80, 5)

with col2:
    # Generar la figura con los parámetros actuales
    fig = generar_figura(q1, q2, x1, x2, y1, y2, epsilon, lim, npts)
    st.pyplot(fig)